allowBuilds:
  canvas: true
  raknet-native: true
blockExoticSubdeps: false
nodeLinker: hoisted
overrides:
  minecraft-data: "github:mc-zuri/node-minecraft-data#bedrock-v2"
  prismarine-chunk: "github:mc-zuri/prismarine-chunk#bedrock"
  prismarine-registry: "github:mc-zuri/prismarine-registry#bedrock"
